- name: 긴급
  color: d73a4a
  description: 긴급한 작업

- name: 문서
  color: 000000
  description: 문서 작업 관련

- name: 취소
  color: FEF2C0
  description: 추후 작업 진행 예정

- name: 작업 완료
  color: 0A4ABB
  description: 작업 완료 상태인 경우 (이슈 폐쇄)

- name: 작업 전
  color: E3F2FD
  description: 작업 시작 전 준비 상태

- name: 작업 중
  color: 74D7CB
  description: 작업이 진행 중인 상태

- name: 취소
  color: f28b25
  description: 작업 취소됨

- name: 확인 대기
  color: FBC61E
  description: 담당자 확인 필요, 대기중 상태 (확인 후 '작업완료' or '피드백')

- name: 피드백
  color: A439D6
  description: 담당자 확인 > 수정 필요
